precision-sustainable-ag/dst-selector

start_script.ps1
- add powershell script equivalent for start_script.sh
=> convert to powershell

.dockerignore, Dockerfile, README.md, start_script.ps1, start_script.sh
Dockerized and updated the readme to be a little bit more verbose
=> dockerized

.dockerignore, Dockerfile, README.md, helm/.helmignore, helm/Chart.yaml, helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/hpa.yaml, helm/templates/ingress.yaml, helm/templates/service.yaml, helm/templates/serviceaccount.yaml, helm/templates/tests/test-connection.yaml, helm/values.yaml, start_script.ps1, start_script.sh
Dockerized as with main, updated readme date, installed helm. This should have zero effect on the application as it is currently deployed.
=> dockerize and helmify

README.md, src/components/CropSelector/CropLegendModal.js, src/components/CropSelector/CropTable.js
THE ISSUE AND THE TASKS DONE IN THE PR
Current issue: currently the word Legend blends into the title bar, the modal takes on the same grey color as the background and the logic for the legend is built into the CropTable file and should be its own component: RESOLVED
Stretch goal: if you are able to quickly resolve the background color issue please do: RESOLVED
=> Issue67: Moved legend modal to seperate component

README.md, src/components/CropSelector/CropTable.js
Current Issue: this file and the whole application really is full of poorly written ternary operators. some examples are below. Please search through all of the ternary operators in this file and look to simplify them: RESOLVED
=> Issue68: Crop table ternary cleanup: DONE

src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/InformationSheetContent/getMonthDayString.js
=> Info sheet

src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparison.js
updated aerial seeding to be recognized by the logic to display info for when aerial seeding is false
=> updated aerial seeding to work properly with the comparion tool

src/pages/Help/Help.js
=> updated help page to fix errors with buttons

src/pages/Header/Header.js, src/pages/Header/InformationBar/InformationBar.js, src/pages/Header/Navbar/Navbar.js, src/pages/Header/ToggleOptions/ToggleOptions.js
Removed the remaining unnecessary ternary operations from files under header
=> Issue139: Header refactor

src/components/CropCard/CropCard.js, src/components/CropDetailsModal/CropDetailsModal.js, src/components/CropSelectorCalendarView/CropSelectorCalendarView.js, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.js, src/pages/CropSelector/CropTable/CropTableCard.js, src/pages/MyCoverCropList/MyCoverCropCards/MyCoverCropCards.js, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparison.js, src/pages/MyCoverCropList/MyCoverCropList.js
Created a reusable component for the crop card that can be used in both the explorer and the myCoverCropList
=> created a crop card to be shared where the card is needed.

src/components/CropCard/CropCard.js, src/components/CropDetailsModal/CropDetailsModal.js, src/components/ImageCarousel/ImageCarousel.js, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.js, src/pages/InformationSheetContent/CoverCropInformation/CoverCropInformation.js, src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparison.js
updated information sheet, link stye added to links, removed top title bar, updated carousel styling and useage, updated formatting for title and description, removed overlapping to my cover crop compare, made cards smaller so more can fit on a screen, adjusted cards, and information sheet to be scalable
=> Many visual updates to carousel, my list, cards, and info sheet

src/components/WeatherConditions/WeatherConditions.js, src/pages/About/About.js, src/pages/MyCoverCropList/ComparisonBar/ComparisonBar.js, src/pages/MyCoverCropList/ComparisonBar/RenderFilters/RenderFilters.js
corrected about section to work properly
=> updated about to work properly

src/components/CropCard/CropCard.js, src/components/TooltipMaker/TooltipMaker.js, src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.js, src/pages/CropSidebar/CropSidebar.js, src/pages/CropSidebar/Filters/Filters.js, src/pages/Header/Header.js, src/pages/Header/InformationBar/InformationBar.js, src/pages/Help/InformationSheetDictionary/InformationSheetDictionary.js, src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/Location/Location.js, src/pages/Location/LocationConfirmation/LocationConfirmation.js, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparison.js, src/shared/ProgressButtons.js, src/store/Reducer.js
the new domain has selector in it and it was always editing the selector sidebar state instead of the explorers
=> fix sidebar

src/pages/GoalsSelector/GoalTag/GoalTag.js
updated tool tips for goals to show when chips are disabled.
=> updated disabled goals to show tool tip on hover

src/pages/CropSidebar/Filters/Filters.js
Removed stars as detailed in the issue, but there is a problem where sometimes the page does not render correctly. Discussed with Mikah in meeting and was told to make the PR anyway (separate issue).
=> fixed stars. Rendering problem exists.

README.md
added fix for the error `Error E404 - Not Found - GET https://registry.npmjs.org/@psa%2fdst.ui.map - Not found`
=> Update registry URL in Readme

.eslintrc.js, README.md, package.json, src/pages/Header/ForecastComponent/ForecastComponent.js, src/pages/Header/Header.js, src/shared/keys.js
updated the weather API URL and changed documentation for .env file location
=> Update weather api

src/pages/Feedback/Feedback.js, src/pages/Landing/Landing.js
Replaced AirTable with custom component.
TODO: Add screenshot functionality to the dst-feedback api
=> Created Custom Feedback Component

src/pages/Landing/Landing.js
Accidentally have spelling mistakes in the branch name sorry.
=> initial commit. full functionalilty added

src/components/CropSelectorCalendarView/CropSelectorCalendarView.js, src/pages/CropSidebar/PreviousCashCrop/DateRangeDialog.js, src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.js
updated prev cash crop date working on calendar.
=> updated prev cash crop to show on calendar.

src/components/CropDetailsModal/CropDetailsModal.js, src/pages/CropSidebar/CropSidebar.js, src/pages/GoalsSelector/GoalsSelector.js, src/pages/Header/Header.js, src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/Landing/Landing.js
updated to the prod api site wide.
=> updated apis to use prod API and not dev

src/components/Legend/Legend.js, src/pages/CropSelector/CropCalendarView/CropCalendarView.js, src/pages/CropSelector/CropTable/CropTable.js, src/pages/CropSidebar/CropSidebar.js, src/styles/cropCalendarViewComponent.scss
updated legend to be dynamic to be used anywhere.  added legend for sidebar.
=> updated legend to be dynamic and added legend info to sidebar

src/pages/Header/Header.js
- weather api call was using obj.state which was undefined
- updated to use obj.abbrState
=> fix weather state

src/pages/Header/Header.js, src/pages/Landing/Landing.js
- zone was getting set to shorthand instead of zone id and wasn't updating correctly when switching addresses
=> fix zone issue

src/pages/Header/Header.js
- fix zone dropdown not updating
=> fixed zone updating

src/pages/Help/InformationSheetDictionary/InformationSheetDictionary.js
Removed bootstrap from InformationSheetDictionary component
=> Remove bootstrap from InformationSheetDictionary component

src/pages/Help/InformationSheetDictionary/DictionaryContent.js
Update styling for dictionary content component by removing bootstrap and unnecessary css
=> Update styling for dictionary content component

src/pages/Header/ForecastComponent/ForecastComponent.js, src/pages/Header/Header.js, src/shared/constants.js
- fix reverse geocoding in weather widget and header
- fix weather tab
=> fix reverse geocoding

src/pages/Header/Header.js, src/pages/Landing/Landing.js
- before it was fetching images, references, and crop data for the incorrect zone and breaking the info sheets
=> fix dictionary

src/pages/Landing/Landing.js, src/pages/Location/Location.js
corrected looping when selectign location on the map then going next.. then back.  
state.state was being set as an object and should have been a string.
=> Looping and undefined state.state 

src/components/CropCard/CropCard.js
- fix blurry placeholder image
=> fix blury placeholder

src/components/CropCard/CropCard.js, src/components/CropCard/RenderRelevantData/RenderRelevantData.js, src/pages/CropSidebar/CropSidebar.js, src/pages/CropSidebar/PlantHardinessZone/PlantHardinessZone.js, src/pages/Header/ForecastComponent/ForecastComponent.js, src/pages/Header/Header.js, src/pages/Header/InformationBar/InformationBar.js, src/pages/Landing/Landing.js, src/pages/Location/Location.js, src/pages/Location/LocationConfirmation/LocationConfirmation.js, src/reduxStore/addressSlice.js, src/shared/ProgressButtons.js
cherry picked from [f75edaa](https://github.com/precision-sustainable-ag/dst-selector/pull/377/commits/f75edaa92159266920b8152f2ad0b781f6d64df7)
completed address state migration
errors to discuss -  GET https://api.covercrop-selector.org/v1/states/undefined/dictionary?regions=undefined 422
=> cherry pick and merge address state

src/App.js, src/components/CropCard/CropCard.js, src/components/CropSelectorCalendarView/CropSelectorCalendarView.js, src/components/MyCoverCropReset/MyCoverCropReset.js, src/components/WeatherConditions/WeatherConditions.js, src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.js, src/pages/CropSelector/CropCalendarView/CropCalendarView.js, src/pages/CropSelector/CropCalendarView/RenderCrops.js, src/pages/CropSelector/CropSelector.js, src/pages/CropSelector/CropTable/CropTable.js, src/pages/CropSelector/CropTable/CropTableCard.js, src/pages/CropSidebar/CropSidebar.js, src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.js, src/pages/GoalsSelector/GoalsSelector.js, src/pages/Header/Header.js, src/pages/Header/HeaderLogoInfo/HeaderLogoInfo.js, src/pages/Header/InformationBar/InformationBar.js, src/pages/Header/ToggleOptions/ToggleOptions.js, src/pages/Landing/Landing.js, src/pages/Location/Location.js, src/pages/Location/SoilCondition/SoilDrainage/SoilDrainage.js, src/pages/MyCoverCropList/MyCoverCropCards/MyCoverCropCards.js, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparison.js, src/pages/MyCoverCropList/MyCoverCropList.js, src/reduxStore/cropSlice.js, src/reduxStore/sharedSlice.js, src/reduxStore/store.js
=> develop/migrate cropSlice

src/components/CropCard/CropCard.js, src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.js, src/pages/CropSidebar/CoverCropSearch/CoverCropSearch.js, src/pages/CropSidebar/CropSidebar.js, src/pages/CropSidebar/Filters/Filters.js, src/pages/Help/InformationSheetDictionary/InformationSheetDictionary.js, src/reduxStore/cropSlice.js, src/reduxStore/filterSlice.js
completed filter data state migration
=> Develop migrate filter data

src/components/CropDetailsModal/CropDetailsModal.js, src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/CropSelector/CropCalendarView/CropCalendarView.js, src/pages/CropSelector/CropTable/CropTable.js, src/pages/CropSidebar/CropSidebar.js, src/pages/CropSidebar/PlantHardinessZone/PlantHardinessZone.js, src/pages/GoalsSelector/GoalsSelector.js, src/pages/Header/HeaderLogoInfo/HeaderLogoInfo.js, src/pages/Header/ToggleOptions/ToggleOptions.js, src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/Landing/Landing.js, src/pages/Location/Location.js, src/pages/Location/LocationConfirmation/LocationConfirmation.js, src/pages/MyCoverCropList/MyCoverCropList.js, src/reduxStore/mapSlice.js, src/reduxStore/store.js, src/shared/ProgressButtons.js, src/shared/ProgressButtonsInner.js, src/store/Reducer.js
- move all map slice info to use redux
=> migrate map slice

src/pages/Header/InformationBar/InformationBar.js, src/pages/Location/SoilCondition/SoilComposition/SoilComposition.js, src/pages/Location/SoilCondition/SoilCondition.js, src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js, src/pages/Location/SoilCondition/SoilDrainage/SoilDrainage.js, src/pages/Location/SoilCondition/SoilFloodingFrequency/RenderFloodingOptions.js, src/pages/Location/SoilCondition/SoilFloodingFrequency/SoilFloodingFrequency.js, src/reduxStore/soilSlice.js, src/store/Reducer.js, src/store/Store.js
- migrate soil slice to redux
- rename same variable to make more sense
- rename soil variables to camelCase
=> migrate soil data

src/components/WeatherConditions/WeatherConditions.js, src/components/WeatherConditions/WeatherFrostDates/WeatherFrostDates.js, src/components/WeatherConditions/WeatherFrostFreeDays/WeatherFrostFreeDays.js, src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.js, src/pages/Header/InformationBar/InformationBar.js, src/pages/Location/Location.js, src/reduxStore/weatherSlice.js
- migrate weather slice
- cleanup some unneeded object passing to dispatch
=> migrate weather slice

src/components/MyCoverCropReset/MyCoverCropReset.js, src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/Header/HeaderLogoInfo/HeaderLogoInfo.js, src/pages/Header/InformationBar/InformationBar.js, src/pages/Header/ToggleOptions/ToggleOptions.js, src/pages/Landing/Landing.js, src/pages/Location/Location.js, src/pages/MyCoverCropList/MyCoverCropList.js, src/shared/ProgressButtons.js, src/shared/ProgressButtonsInner.js
- Replaced Dialogs with custom component MyCoverCropReset.
- Updated logic for whether to show the dialogs.
- Updated props for MyCoverCropReset to implement the functionality in InformationBar.js and HeaderLogoInfo.js.
=> Feature/406 Replaced Dialogs with custom component

src/pages/GoalsSelector/GoalsSelector.js
Update styling and remove bootstrap from Goals Selector component
=> Remove bootstrap from Goals Selector component

src/App.js, src/index.js, src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/CropSelector/CropSelector.js, src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/Location/Location.js
- handle url params to auto open pdfs
- example url http://localhost:3000/?crop=Barley,%20Spring^&state=37^&region=58
- important to note the carats between params, this is needed for it to work
- remove last state vars
- remove store wrapper from index.js
=> fix pdf urls

src/pages/Location/LocationConfirmation/LocationConfirmation.js, src/shared/ProgressButtonsInner.js
added soil conditions component back into view when in the Midwest council.
=> added soil conditions back to MCCC

src/pages/Location/SoilCondition/SoilFloodingFrequency/RenderFloodingOptions.js
updated flooding chips to remove none when something else is selected and only allow none when none is selected.
=> updated flooding chips to work better with none option being an absolute

src/pages/CropSelector/CropCalendarView/CropCalendarView.js, src/pages/CropSelector/CropTable/CropTable.js, src/shared/constants.js
Fixes #374 
- Added sorting algorithm to constants.js
- Added a button on the crop calendar view page for sorting
- Added a button on the crop list view page
=> Added sorting algorithm for crop group

package.json, src/pages/Landing/Landing.js
- Updated Landing.js logic to let it fit the updated region-selector map. Now the map would only show available states based on current environment(dev/prod).
- Once the user selected a state and proceed, when they get back to the page the map could recover the state that they used to select, which contributes to user experience.
- Removed some unused lines, improve consistency.
=> Update landing map

src/shared/constants.js
- Modified moment usage in calculating plant growth windows, now moment could accept correct time.
=> Fix Firefox not shown plant growth window problem

package.json, src/pages/Location/Location.js, src/pages/Location/LocationConfirmation/LocationConfirmation.js, src/reduxStore/userSlice.js
- Remove conditional on LoactionConfirmation to let the map always shown.
- Add a redux state for selected field so when the user come back to the Location page the selected field will be auto located.
=> Fix location confirmation map

src/pages/InformationSheetContent/InformationSheetContent.js, src/reduxStore/goalSlice.js, src/shared/constants.js
updated comments section to be easier to see and read.
=> updated comments section for midwest infosheet to be styled better

src/pages/Landing/Landing.js
- use default region for the selected state so that the explorer has a zone populated on first render
=> use default region

src/components/CropSelectorCalendarView/CropPaintGrowthChart/CropPaintGrowthChart.js, src/components/Legend/Legend.js, src/shared/constants.js, src/styles/constants.scss, src/styles/cropCalendarViewComponent.scss
Solves #464 
Changes made to:
`constants.js`
`CropPaintGrowthChart.js`
=> Added a diamond for fly free dates - mainly for mccc

src/pages/Location/Location.js
This PR contains updates for fixing issue https://github.com/precision-sustainable-ag/dst-selector/issues/483
RCA: Annual and monthly precipitation were storing the API results in the same-named variable and there was some issue in asynchronous API calls (API calls were synchronous actually). Hence, both annual and monthly precipitation were displaying the same value based on the which API call returned the results first.
Update: Updated asynchronous structure using async-await format
=> Fix async issue for monthly and annual precipitation

src/pages/CropSelector/CropTable/CropTableListItem.js, src/pages/Header/Header.js
- update favicon on state change
- update logo on state change
- update DOM elements with useRef
=> Update Header.js and Croptablelistitem.js

src/components/WeatherConditions/WeatherConditions.js
- remove the weather edit modal
- remove related code
=> Remove weather editing modal

src/pages/CropSidebar/CropSidebar.js
- fix crops being filtered by drainage class by default
=> fix filtering on drainage class

src/shared/constants.js
This PR has fixes for https://github.com/precision-sustainable-ag/dst-selector/issues/502
Updated constants.js file to provide list of filters for NECCC
=> Update legend for NECCC by removing hessian fly filter

src/pages/CropSelector/CropCalendarView/RenderCrops.js, src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.js
- Left align cover crop names in the calendar view
- Make cover crop name text black instead of light green
=> update text color and fix crop name left align

src/App.js
center the main section(between header and footer)
=> center the main section

src/pages/CoverCropExplorer/CoverCropExplorer.js, src/pages/CropSelector/CropSelector.js, src/pages/CropSidebar/CropSidebar.js, src/pages/MyCoverCropList/MyCoverCropListWrapper/MyCoverCropListWrapper.js
Added a button for both list view and calendar view separately and highlight the activated page.
=> updated cal view and list view button to have separate buttons

src/pages/Header/Header.js, src/pages/Help/FAQ/FAQ.js, src/pages/Help/Help.js, src/pages/Help/HowTo/HowTo.js, src/pages/Help/InfoSheets/InfoSheets.js
This PR is for updating the help section into multiple components and to make help available only after state selection.
=> updated help to separate sections out into individual components

src/pages/Location/SoilCondition/SoilCondition.js, src/shared/ProgressButtons.js
- handle Ontario logic in progress-buttons
- repositioned the base case in soil-conditions page to fix the flow
=> fix-ontario-flow

src/shared/constants.js
- make clean grid for attribute values
- right align values
=> final UI for attribute values

src/shared/constants.js
Reverts precision-sustainable-ag/dst-selector#560
=> Revert "final UI for attribute values"

src/pages/CropSidebar/Filters/Filters.js
tooltip body needs to be in a span updated tooltip for sidebar.
=> updated tooltips on sidebar to work properly

src/pages/CropSidebar/Filters/Filters.js, src/shared/constants.js
=> release 02-27-24

src/pages/InformationSheetContent/CoverCropInformation/CoverCropInformation.js, src/pages/InformationSheetContent/InformationSheetContent.js
- bugfix release to fix descriptions in info sheet
=> Release 02-28-24

src/components/WeatherConditions/WeatherFrostDates/WeatherFrostDates.js, src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.js, src/pages/Location/SoilCondition/SoilComposition/SoilComposition.js
- change gray text to black
- increase text size
=> change styles in site conditions

src/shared/constants.js
- includes handling fix for the comparison table edge case
=> display multiple attribute values

src/pages/CropSelector/CropCalendarView/RenderCrops.js, src/pages/CropSelector/CropTable/RenderTableItems.js, src/shared/constants.js
- Change font sizes a bit in table view and list view
- Underline crop names in calendar and list view
- On hover of crop name, remove underline
- Fix bug in string truncating logic
=> make crops more obviously clickable

src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.js
- Fix comparison view not showing no data
=> release 03-01-24

src/pages/InformationSheetContent/InformationSheetContent.js, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.js, src/shared/constants.js
updated constants.js so that comparison table can hold multiple values in each cell
=> updated constants.js

src/components/ImageCarousel/ImageCarousel.js
- Fixed image attribution to be `Source: <name>, <year>`
=> add attribution back

src/shared/constants.js
=> add units to info sheet

src/shared/constants.js
- remove average frost from legend
- remove multiple from legend now that it's no longer possible to have multiple
=> remove average frost

src/App.js, src/components/Auth/AuthButton/AuthButton.js, src/pages/Header/Header.js, src/pages/Landing/AuthModal/AuthModal.js
- update login colors to have higher contrast and be easier to read
=> fix color contrast issues

src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.js, src/shared/constants.js
- fix undefined units on comparison view
=> fix undefined units

src/pages/Location/Location.js
=> use new phz api

src/pages/CropSidebar/CropSidebar.js
- use council shorthand to update sidebar legend
=> use council shorthand to update sidebar legend

src/pages/Header/Header.js, src/pages/Location/Location.js, src/pages/Location/UserFieldDialog/UserFieldDialog.js, src/reduxStore/userSlice.js, src/shared/authToken.js
- Removed auth token from redux store, save it in memory instead so the user would not have direct access to it.
Closes #609
=> Update storing for auth token

src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.js, src/pages/MyCoverCropList/MyCoverCropList.js
- fix crop list being filtered
=> fix crop list being filtered

src/pages/InformationSheetContent/InformationSheetContent.js
- Remove buggy document.title change logic for info sheet
=> fix title change bug

src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.js
=> fix average goal rating bug

README.md
=> remove prettier from readme

src/components/CropCard/CropCard.js, src/components/HistorySelect/HistorySelect.js, src/pages/CropSelector/CropCalendarView/RenderCrops.js, src/pages/CropSelector/CropTable/CropTableCard.js, src/pages/Header/Header.js, src/pages/Header/SaveUserHistory/SaveUserHistory.js, src/reduxStore/userSlice.js, src/shared/ProgressButtonsInner.js, src/shared/api.js, src/shared/constants.js
- Added message for user history loading, saving and error.
- Updated user history api structure.
=> Add snackbar message for user history

src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js, src/pages/Location/SoilCondition/SoilDrainage/SoilDrainage.js, src/reduxStore/soilSlice.js
- Created redux for tile drainage.
- Updated tile drainage logic so the selection will be keep through page change.
=> Fix tile drainage

src/pages/Landing/Landing.js
expanded state dropdown and map boxes to be wider on smaller resolutions.
=> updated landing page to widen boxes on smaller windows

src/pages/CropSelector/CropCalendarView/CropCalendarView.js, src/pages/CropSelector/CropSelector.js, src/pages/CropSelector/CropTable/CropTable.js, src/pages/CropSidebar/CropSidebar.js, src/pages/Footer/Footer.js, src/pages/Header/Header.js, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.js, src/pages/MyCoverCropList/MyCoverCropListWrapper/MyCoverCropListWrapper.js, src/reduxStore/pageSlice.js, src/reduxStore/store.js
What done looks like
- Calendar, list, and comparison view tables have sticky headers
Where the changes need to be made
- Calendar view
- List view
- Comparison view
=> Fix - sticky table headers

README.md, src/pages/Header/Header.js, src/shared/keys.js
added a link to the header to include a link opening in a new tab to the release notes.
=> updated header to have release notes button

azure/develop-pipelines.yml
=> release 8-9-24

src/components/HistoryDialog/HistoryDialog.js, src/pages/CropSidebar/CoverCropSearch/CoverCropSearch.js, src/pages/Feedback/Feedback.js, src/pages/Location/UserFieldDialog/UserFieldDialog.js, src/shared/PSATextField.js
Implemented the PSATextField in the following files:
HistoryDialog.js
CoverCropSearch.js
Feedback.js
UserFieldDialog.js
=> Implemented PSATextField Component

src/pages/CropSelector/CropSelector.js, src/pages/Footer/Footer.js, src/pages/Header/Header.js, src/shared/constants.js
I added a useEffect that would check the size of the current window and use it to dynamically resize the header and footer to match the screen size.
=> Feature 679 managing header/footer size

vite.config.js
Updated vite config to fix dev branch
=> Fix develop

src/pages/CropSidebar/CropSidebar.jsx, src/reduxStore/filterSlice.jsx
Updated the sidebar to include a filter for cover crop group.
=> updated sidebar filter to include crop groups

src/pages/CropSidebar/CropSidebar.jsx
added an update to fix the filters that were broken because of the cover group group logic
=> updated crop group filter

src/pages/CropSidebar/CoverCropSearch/CoverCropSearch.jsx
Implementing the PSATextfield in the selector
=> Implementing PSATexfield

package.json, src/pages/Header/Header.jsx
- Updated header component with updated prop, added <PSAAuthButton /> as custom component to the header
=> Update Header with new prop

package-lock.json, package.json, src/pages/CropSelector/CropSelector.jsx, src/pages/CropSidebar/CropSidebar.jsx
https://github.com/precision-sustainable-ag/dst-selector/issues/692
=> sizing changes adapted

package-lock.json, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.jsx, src/pages/CropSelector/CropCalendarView/CropCalendarView.jsx, src/pages/CropSelector/CropTable/CropTable.jsx, src/pages/GoalsSelector/GoalsSelector.jsx, src/pages/Location/SoilCondition/SoilCondition.jsx
Integrated the shared Loading Spinner
=> Connect PSALoadingIcon shared component to selector #723

Dockerfile, package-lock.json, src/components/HistorySelect/HistorySelect.jsx, src/pages/CoverCropExplorer/ExplorerCardView/ExplorerCardView.jsx, src/pages/CropSelector/CropCalendarView/CropCalendarView.jsx, src/pages/CropSelector/CropTable/CropTable.jsx, src/pages/GoalsSelector/GoalsSelector.jsx, src/pages/Header/Header.jsx, src/pages/Header/ToggleOptions/ToggleOptions.jsx, src/pages/InformationSheetContent/InformationSheetReferences/InformationSheetReferences.jsx, src/pages/Landing/Landing.jsx, src/pages/Location/Location.jsx, src/pages/Location/SoilCondition/SoilCondition.jsx, src/shared/ProgressButtonsInner.jsx
- Updated Landing page styling to remove scroller.
- Fix bugs with shared button and tooltip.
- Resolve console warnings for shared components.
- Update dependencies and naming.
=> Styling updates

azure/develop-pipelines.yml, src/pages/CropSidebar/CropSidebar.jsx
Removed features added for west data for dev branch
=> removed west features for develop

cypress/e2e/landing-e2e.cy.js, package-lock.json, package.json, src/shared/constants.jsx
1. Made the separate sorting functions based on the types
2. Made the funtion to compare the values
3. Made the function to get the average of the crop goal
4. Made the function to sort the data by Crop name
5. Created a function to create the Reliable Establishment Date
=> Refactor Sorting function in constants.js #754

package-lock.json, src/App.jsx, src/components/CropSelectorCalendarView/CropSelectorCalendarView.jsx, src/components/Legend/Legend.jsx, src/components/SkipContent/SkipContent.jsx, src/components/WeatherConditions/WeatherFrostDates/WeatherFrostDates.jsx, src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.jsx, src/pages/CoverCropExplorer/CoverCropExplorer.jsx, src/pages/CropSelector/CropCalendarView/CropCalendarView.jsx, src/pages/CropSelector/CropCalendarView/RenderCrops.jsx, src/pages/CropSelector/CropSelector.jsx, src/pages/CropSidebar/CoverCropGoals/CoverCropGoals.jsx, src/pages/CropSidebar/CropSidebar.jsx, src/pages/CropSidebar/Filters/Filters.jsx, src/pages/CropSidebar/SidebarFilter/SidebarFilter.jsx, src/pages/Footer/Footer.jsx, src/pages/InformationSheetContent/InformationSheetContent.jsx, src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.jsx, src/pages/MyCoverCropList/ComparisonBar/RenderFilters/RenderFilters.jsx, src/pages/MyCoverCropList/ComparisonBar/RenderGoals/RenderGoals.jsx, src/shared/constants.jsx
- Fixed missing keyboard navigation functionality and updated focused styling for components on several pages.
- Created skip content button across multiple pages and forms.
=> Updated keyboard navigation and skip content

src/components/CropDetailsModal/CropDetailsModal.jsx, src/components/ImageCarousel/ImageCarousel.jsx, src/pages/InformationSheetContent/CoverCropInformation/CoverCropInformation.jsx, src/pages/InformationSheetContent/InformationSheetContent.jsx, src/reduxStore/sharedSlice.jsx, src/styles/App.scss
- Added pdf export functionality which uses an export-pdf endpoint to generate pdf based on the html rather than pre-generated pdfs.
=> Export PDF

package-lock.json, src/components/CropSelectorCalendarView/CropSelectorCalendarView.jsx, src/components/WeatherConditions/WeatherFrostDates/WeatherFrostDates.jsx, src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.jsx, src/pages/CropSelector/CropCalendarView/CropCalendarView.jsx, src/pages/CropSelector/CropCalendarView/RenderCrops.jsx, src/pages/CropSelector/CropTable/CropTable.jsx, src/pages/CropSidebar/CropSidebar.jsx, src/pages/CropSidebar/Filters/Filters.jsx, src/pages/CropSidebar/SidebarFilter/SidebarFilter.jsx, src/pages/GoalsSelector/GoalTag/GoalTag.jsx, src/pages/Location/SoilCondition/SoilComposition/SoilComposition.jsx, src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.jsx, src/pages/Location/SoilCondition/SoilDrainage/SoilDrainage.jsx, src/pages/Location/SoilCondition/SoilFloodingFrequency/SoilFloodingFrequency.jsx, src/pages/MyCoverCropList/ComparisonBar/RenderFilters/RenderFilters.jsx, src/shared/ProgressButtonsInner.jsx, src/shared/constants.jsx
- Added missing aria labels for shared components and components across the app.
- Fixed annotations for tooltips
=> Fix annotations across the app

src/components/CropDetailsModal/CropDetailsModal.jsx, src/pages/InformationSheetContent/InformationSheetContent.jsx, src/styles/App.scss
- styling changes for consistent pdf's on all sized devices
- updated pdf generation url to point to new api
=> Fix pdf mobile view

src/components/CropDetailsModal/CropDetailsModal.jsx, src/pages/CropSidebar/CropSidebar.jsx, src/pages/GoalsSelector/GoalsSelector.jsx, src/pages/Header/InformationBar/InformationBar.jsx, src/pages/InformationSheetContent/InformationSheetContent.jsx, src/pages/Landing/Landing.jsx, src/pages/Location/Location.jsx, src/pages/Location/SoilCondition/SoilCondition.jsx, src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.jsx, src/pages/Location/SoilCondition/SoilDrainage/SoilDrainage.jsx, src/reduxStore/mapSlice.jsx, src/shared/ProgressButtons.jsx, src/shared/ProgressButtonsInner.jsx
- Fixed map jumping issue.
- Updated setQueryString logic from Location to Landing.
- Removed zone dropdown in Location page and Explorer in wccc
- Fixed a few apis to make them working with queryString
- Fixed soil drainage selection in wccc
=> Fix location page and queryString in wccc

src/components/CropSelectorCalendarView/CropSelectorCalendarView.jsx, src/pages/CropSidebar/CropSidebar.jsx, src/pages/CropSidebar/PlantHardinessZone/PlantHardinessZone.jsx, src/shared/constants.jsx, src/styles/cropSelectorCalendarView.scss
- Added function for filtering irrigation windows in wccc.
- Updated legend for wccc crop calendar.
- Fixed a problem that querystring is not correctly update in zone dropdown.
=> Add wccc irrigation filter function

src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.jsx
=> Adds clear button for cash crop window

src/components/CropCard/CropCard.jsx, src/pages/CropSelector/CropCalendarView/RenderCrops.jsx, src/pages/CropSelector/CropTable/RenderTableItems.jsx, src/pages/CropSidebar/CropSidebar.jsx
added a soil drainage filter for WA ER 7
It borders the crops with red color which has 'Excessively Drainage' as one of the soil drainage options
=> WCCC requirement: species filtering based on drainage, tiling, and irrigation #546

src/pages/Footer/Footer.jsx, src/pages/Header/InformationBar/InformationBar.jsx, src/shared/NavigationButtons.jsx
=> Adds nav buttons to all pages

package-lock.json, src/pages/CropSidebar/CropSidebar.jsx
Fixed issue of checking optional attribute 'Cover Crop Group'
=> Fix Search Crop Name Feature

src/components/CropSelectorCalendarView/CropSelectorCalendarView.jsx, src/components/Legend/Legend.jsx, src/shared/constants.jsx, src/styles/constants.scss, src/styles/cropCalendarViewComponent.scss, src/styles/cropSelectorCalendarView.scss
- Added color for can interesed(For eg- NECCC-Zone6-Forage Radish) in constants.scss and cropcalenderview.scss.
- removed .late and .early classes
- added interseed in NECCC legend
=> color added for can interested

src/pages/GoalsSelector/GoalsSelector.jsx, src/pages/InformationSheetContent/InformationSheetContent.jsx, src/reduxStore/store.jsx, src/reduxStore/terminationSlice.jsx, src/shared/ProgressButtonsInner.jsx
Implementing the Additional Filters section in the goals tab
=> Implementing Additional Filters

src/components/HistorySelect/HistorySelect.jsx, src/shared/api.jsx
User now have an option to delete history along with import.
=> delete history implemented

src/pages/Help/FAQ/FAQ.jsx, src/shared/constants.jsx
=> wccc faqs integrated

src/pages/CropSidebar/CropSidebar.jsx, src/pages/GoalsSelector/GoalsSelector.jsx
- Removed termination filter in WCCC
- Updated goals page filter name
=> Remove termination filter in wccc

src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.jsx, src/reduxStore/soilSlice.jsx
Fixed the issue where the drainage class would decrement when leaving the initial page.
=> implementing bug fix

src/components/CropCard/CropCard.jsx
Set the sideways images to be rotated by 90 degree right to get it correctly oriented
=> Fix the sideway images

src/pages/InformationSheetContent/InformationSheetContent.jsx
Frontend - Removed unnecessary text - order which was putting number after the ecoregion and state like 100
Database - Renamed and merged both of the attributes to one attribute only
=> Problem with WCCC Notes #815

src/pages/CropSelector/CropTable/CropTable.jsx, src/pages/CropSelector/CropTable/RenderTableItems.jsx
- Entire table width in 100 view width.
- First crop image column as sticky and then all either column horizontally scrolabele behind the first column.
=> Implemented mobile view for crop table.

src/pages/Landing/Landing.jsx
=> User history state change fix

src/pages/CropSidebar/CropSidebar.jsx, src/pages/GoalsSelector/GoalsSelector.jsx, src/pages/Header/Header.jsx
=> updated demo to include minor updates from preview

package-lock.json, src/pages/CropSidebar/CropSidebar.jsx
Updated the 'Flood' attribute label as it's different for NECCC and other councils to make the flooding frequency filter work correctly
=> WCCC - Flooding Frequency - Wash, Cali, NV... BUG #843

src/pages/InformationSheetContent/InformationSheetContent.jsx
Fix the UI for termination WCCC
- Before
-After
=> FIx the UI for termination WCCC

src/pages/GoalsSelector/GoalTag/GoalTag.jsx, src/pages/GoalsSelector/GoalsSelector.jsx, src/pages/InformationSheetContent/InformationSheetContent.jsx, src/pages/MyCoverCropList/MyCoverCropComparison/MyCoverCropComparisonTable.jsx, src/reduxStore/terminationSlice.jsx, src/shared/constants.jsx
- Updated `tags` information with goals selection.
- Filter WCCC `Termination Window` info based on `tags` selection.
=> Update WCCC Termination Window filter based on tags

package-lock.json, package.json, src/pages/Location/Location.jsx, src/pages/Location/StateChangeAlertDialog/StateChangeAlertDialog.jsx, src/reduxStore/sharedSlice.jsx
- Address #803 
- This PR closes the first two points of the issue. The third point will be covered in another PR
=> WCCC map updates

package-lock.json, package.json, src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.jsx, src/shared/constants.jsx
- Updated cash crop date picker for restrictions to select end date after start date.
- Updated calendar page logic for showing cash crop window over a year.
=> Updats for cash crop date selection

src/pages/GoalsSelector/GoalsSelector.jsx
- Updated titles for additional filters on goal selector page.
=> Update titles for additional filters

src/pages/CropSelector/CropCalendarView/CropCalendarView.jsx, src/pages/CropSelector/CropTable/CropTable.jsx
Set the initial sort based on the goals selected instead of planting window for WCCC
=> Update initial sort for WCCC #878

azure/develop-pipelines.yml, azure/production-pipelines.yml, cypress.config.mjs, cypress/e2e/user-history.cy.js, dev.cypress.config.mjs, package-lock.json, src/components/Auth/Auth0ProviderWithHistory/Auth0ProviderWithHistory.jsx, src/pages/Landing/Landing.jsx, src/reduxStore/sharedSlice.jsx, src/shared/ProgressButtons.jsx, src/shared/keys.jsx
- Created fake Auth0Provider component to make test build work without auth0 environment.
- Updated pipelines to make it run on relevant branches.
- Added test auth0 env for develop pipelines to use fake Auth0Provider in develop build.
- Updated api urls on pipeline builds.
- Fixed Location page to work on pipeline builds without map functions.
=> Update pipelines for creating available build on pr creation and update

src/components/WeatherConditions/WeatherConditions.jsx, src/components/WeatherConditions/WeatherFrostDates/WeatherFrostDates.jsx, src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.cy.jsx, src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.jsx, src/pages/Location/Location.jsx, src/pages/SiteConditions/SiteConditions.cy.jsx, src/pages/SiteConditions/SiteConditions.jsx, src/reduxStore/weatherSlice.jsx
- Updated calculation for `Frost Free Days`.
- Removed default values for `Frost Free Days` and `Precipitation`
- Hide `Precipitation` section when no data is available.
=> Fix weather info

src/pages/Landing/Landing.jsx
only show AL and HI on develop and local
=> remove additional states on prod

src/pages/Landing/Landing.jsx
- remove AK and HI from the map in production
=> release 06-05-25 

src/pages/Location/Location.jsx
Updated 'Find your address' to 'Enter your address'
=> It should say "enter your address" not "find your address" #893

package-lock.json, src/pages/Landing/Landing.jsx, src/pages/Location/Location.jsx
=> Add explanation of the asterisk on "state" #892

src/pages/GoalsSelector/GoalTag/GoalTag.jsx, src/pages/GoalsSelector/GoalsSelector.jsx
1. Removed the black border
2. Fixed the selected goals order issue
=> Goals selection scrambles order when selecting and deselecting. #896

src/components/WeatherConditions/WeatherPrecipitation/WeatherPrecipitation.jsx, src/pages/Help/InformationSheetDictionary/InformationSheetDictionary.jsx, src/pages/SiteConditions/SoilCondition/SoilDrainage/SoilDrainage.jsx, src/pages/SiteConditions/SoilCondition/SoilFloodingFrequency/SoilFloodingFrequency.jsx
- Updated links for Precipitation tooltip.
- Updated links for Drainage Class and Flooding Frequency to data dictionary, added link for ssurgo definitions in data dictionary.
=> Update links on site condition page

src/components/InformationSheet/ImageCarousel/ImageCarousel.jsx
Added a pause button to the fact sheet carousels and slowed down the changing time
=> Slowing down carousel and making it pausable:

src/pages/CropSidebar/CropSidebar.jsx, src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.jsx, src/pages/GoalsSelector/GoalsSelector.jsx
- Split goals selection to two columns, update the wccc additional filter placement.
- Rename lifecycle to cropping system.
- Remove crop filtering for irrigate filter.
- Add crop filtering for first selected goal.
=> Updates for goals page

src/App.jsx
- The logger will only trigger on dev or prod url
=> Update url for error logger

src/pages/CropSidebar/CropSidebar.jsx
Making sure that crop search works for plural words/singular words
=> Implementing Crop Search Improvements

src/pages/CropSidebar/CropSidebar.jsx
- Updated crop filtering function, filter out crops without related filter attribute.
=> Update logic for crop without attribute

src/pages/CropSelector/CropCalendarView/RenderCrops.jsx, src/pages/CropSelector/CropTable/CropTableCard.jsx, src/pages/CropSidebar/CropSidebar.jsx, src/shared/constants.jsx
Now, sorting by 'My Crops' would also get the selected grayed out ones on the top and if they gets unselected after then again they will be grayed out and get in the bottom
=> Sorting by "My List" does not bring all the selected crops to the top. The grayed-out ones are still in the bottom portion #933

package-lock.json, src/pages/SiteConditions/SoilCondition/SoilCondition.jsx, src/pages/SiteConditions/SoilCondition/SoilDrainage/SoilDrainage.jsx, src/pages/SiteConditions/SoilCondition/SoilFloodingFrequency/SoilFloodingFrequency.jsx
- Fixed a problem that in Site Conditions page the size for boxes for drainage and flooding not aligning.
- Updated shared component version.
=> Fix Site Condition styling

package-lock.json, src/components/CropCard/CropCard.jsx
- Fixed vertical shift issue when scrolling in explorer page by adding default height to crop card.
- Updated props for crop cards.
- Fixed crop image reloading issue.
=> Fix bugs with crop card

src/App.jsx
Added the Redux store with the required slices when the feedback api gets called
=> Add redux state to crash reports #948

src/components/CropCard/CropCard.jsx, src/pages/CropSelector/CropCalendarView/RenderCrops.jsx, src/pages/CropSelector/CropTable/RenderTableItems.jsx, src/pages/CropSidebar/CropSidebar.jsx, src/reduxStore/filterSlice.jsx
- Update logic for filtering crops by soil drainage in WCCC. The filtering now became an selectable option on crop calendar / list page.
- Updated additional soil drainage filtering with updates from backend.
=> Update soil drainage filtering and additional soil drainage filtering

src/pages/CropSidebar/PreviousCashCrop/PreviousCashCrop.jsx, src/pages/GoalsSelector/GoalsSelector.cy.jsx, src/shared/constants.jsx
updated final small text updates per WCCC
=> updated text for Nathan Stacy's credit and cash crop growing window text

src/pages/Landing/Landing.jsx
=> updated wccc states

src/pages/SiteConditions/SoilCondition/SoilCondition.jsx
- Updated soil condition logic
=> Fix for app crash in Ontario
